test_cmdcallback: fix race condition on t_lock
Apparently onFinished was being called during construction
and therefore the subclass instance variables hadn't been
set:

```
   Traceback (most recent call last):
     File "target/omero/callbacks.py", line 300, in finished
       self.onFinished(rsp, status, current)
     File "test/integration/test_cmdcallback.py", line 51, in onFinished
       self.t_lock.acquire()
   AttributeError: 'CmdCallback' object has no attribute 't_lock'
```

see:
https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-integration-python/935/testReport/junit/OmeroPy.test.integration.test_cmdcallback/TestCmdCallback/testDoNothingFinishesOnLoop/